// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rrzekdyumrwvzavuymtg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJyemVrZHl1bXJ3dnphdnV5bXRnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1MDk1OTAsImV4cCI6MjA2MTA4NTU5MH0.0QhNFWEzViT0xSoROfxYn4W0OPWqNJDLJUI7IuCDg-0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);